/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Adam' at '5/23/16 1:17 PM' with Gradle 2.9
 *
 * @author Adam, @date 5/23/16 1:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
